### ISSUE TITLE
Chapter 7 - page 147 - The default() Filter - Example: "Ensure nginx status is enabled"

### ISSUE THREAD

**Issue by gmaubach** [Apress/Beginning-Ansible-Concepts-and-Application#2]
Dear Shaun,
I tried your example for webservers.yaml:
```yaml
    - name: Ensure nginx status is enabled
      blockinfile:
        path: /etc/nginx/sites-enabled/default
        insertafter: "server {"
        block: |
          location /{{status_url | default('status')}} {
            stub_status on;
          }
```
Running ansible-playbook ./play/webservers.yaml resulted in:

```text
TASK [Reload nginx for new config] *************
fatal: [web-001.local]: FAILED! => changed=false 
  msg: |-
    Unable to reload service nginx: Job for nginx.service failed.
    See "systemctl status nginx.service" and "journalctl -xe" for details.
fatal: [web-002]: FAILED! => changed=false 
  msg: |-
    Unable to reload service nginx: Job for nginx.service failed.
    See "systemctl status nginx.service" and "journalctl -xe" for details.
```
sudo nginx -t gives
```text
nginx: [emerg] "location" directive is not allowed here in /etc/nginx/sites-enabled/default:81
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Resulting /etc/nginx/sites-enabled/default file is attached.

How can I solve my issue?

Best Regards

Georg
[etc_nginx_sites-enabled_default.txt](https://github.com/Apress/Beginning-Ansible-Concepts-and-Application/files/14647507/etc_nginx_sites-enabled_default.txt)
